language: node_js
node_js:
  - "node"
env:
  - HUSKY=0
  - CODECOV_TOKEN="88b89344-8051-4bc1-aa42-f6428b99355b"
cache:
  directories:
    - node_modules
before_install:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
before_script:
  - npm run lint
script:
  - npm test
after_success:
  - ./codecov -t ${CODECOV_TOKEN} -f coverage/lcov.info
